# This file was generated by GoReleaser. DO NOT EDIT.
class Jen < Formula
  desc "Software to easily generate JWTs"
  homepage "https://github.com/benfdking/jen"
  version "0.11.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/benfdking/jen/releases/0.11.0/jen_0.11.0_Darwin_x86_64.tar.gz"
    sha256 "9d45874b0f9b9c8c319585f468e874cfb75ad1257448eea86e2d107bf3fe2817"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/benfdking/jen/releases/0.11.0/jen_0.11.0_Linux_x86_64.tar.gz"
    sha256 "f068d4abbc9adaacb5d27c88be673fc3bbcb83fb9cdf95e9529ccf0559a1b311"
  end

  def install
    bin.install "jen"
  end
end
